### ISSUE TITLE
👁️👄👁️

### ISSUE THREAD

**Issue by hanatic** [Thisisniceygy/aams-console-example#1]
Olivia have you not worked out how to set your repos to private 👁️👄👁️

**Comment by Thisisniceygy** [comment]
its using gh pages 😅 so i dont think i can  (https://aams.niceygylive.xyz)

**Comment by hanatic** [comment]
You can

**Comment by hanatic** [comment]
Never mind, that needs a premium account. Ignore me.

**Comment by hanatic** [comment]
You also spelt the "access" in RAM wrong.

**Comment by Thisisniceygy** [comment]
Yes.... My spelling isn't my strong point 🤣

**Comment by Thisisniceygy** [comment]
Also... How do you do that readme.md on your public profile page? The one in hanatic/readme.md

**Comment by hanatic** [comment]
Just make a repo with the same name as your username. Then whatever content is in the README gets displayed on your profile - got added around 6 months ago
